// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Triplog.Entries.Infrastructure.Persistence;

#nullable disable

namespace Triplog.Entries.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TriplogEntriesDbContext))]
    [Migration("20260729125042_AddPublishEntrySagaState")]
    partial class AddPublishEntrySagaState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Triplog.Entries.Domain.Entries.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastPublishFailReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_publish_fail_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateOnly>("VisitedOn")
                        .HasColumnType("date")
                        .HasColumnName("visited_on");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_entries_owner_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_entries_trip_id");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Triplog.Entries.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dates", "Triplog.Entries.Domain.Trips.Trip.Dates#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("dates_end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("dates_start_date");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_trips_owner_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Triplog.Entries.Infrastructure.Persistence.Sagas.PublishEntrySagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<int>("FinalizedCount")
                        .HasColumnType("integer")
                        .HasColumnName("finalized_count");

                    b.Property<string>("FirstFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("first_failure_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("TotalMediaCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_media_count");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CorrelationId")
                        .HasName("pk_publish_entry_saga_state");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("ix_publish_entry_saga_state_current_state");

                    b.ToTable("publish_entry_saga_state", (string)null);
                });

            modelBuilder.Entity("Triplog.Entries.Domain.Entries.Entry", b =>
                {
                    b.OwnsOne("Triplog.Entries.Domain.Common.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location_name");

                            b1.HasKey("EntryId");

                            b1.ToTable("entries");

                            b1.WithOwner()
                                .HasForeignKey("EntryId")
                                .HasConstraintName("fk_entries_entries_id");
                        });

                    b.OwnsMany("Triplog.Entries.Domain.Entries.MediaReference", "MediaReferences", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("entry_id")
                                .HasColumnType("uuid")
                                .HasColumnName("entry_id");

                            b1.HasKey("id")
                                .HasName("pk_entry_media_references");

                            b1.HasIndex("entry_id", "Id")
                                .IsUnique()
                                .HasDatabaseName("ix_entry_media_references_entry_id_id");

                            b1.ToTable("entry_media_references", null, t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("entry_id")
                                .HasConstraintName("fk_entry_media_references_entries_entry_id");
                        });

                    b.Navigation("Location");

                    b.Navigation("MediaReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
